import { asset } from './asset'

/* ================================================================== *
 *  FLYTHROUGH SEQUENCE — SINGLE SOURCE OF TRUTH
 * ================================================================== *
 *
 *  The cinematic drone flythrough is a scroll-scrubbed WebP frame
 *  sequence (extract ~12.5fps → 125 frames for the 10s Kling take,
 *  per PRD §4/§8). Right now it plays against PROCEDURAL PLACEHOLDER
 *  frames generated by `scripts/gen-dummy-frames.mjs` into
 *  `public/seq/flythrough/` — so the whole pinned scene is fully built
 *  and verifiable before the real AI video exists.
 *
 *  DROPPING IN THE REAL FRAMES IS A ONE-LINE SWITCH:
 *    1. Extract the approved Kling take to
 *         public/seq/flythrough/frame_0001.webp … frame_0125.webp
 *       (same folder, same zero-padded names).
 *    2. Set  USE_DUMMY_FRAMES = false  below.
 *    3. If the real take yields a different frame count, update
 *       REAL_FRAME_COUNT to match.
 *  Nothing else in the app needs to change.
 * ================================================================== */

/** true = on-disk placeholder frames + a "placeholder" marker overlay. */
export const USE_DUMMY_FRAMES = false

/** Folder under /public that holds frame_####.webp (base-aware at runtime). */
export const FRAME_DIR = 'seq/flythrough'

/** Real take: 10.08s Kling @ 12.5fps → 126 frames on disk. */
export const REAL_FRAME_COUNT = 126

/** Frames the placeholder generator writes (kept in sync with the script). */
export const DUMMY_FRAME_COUNT = 125

/** Frames currently on disk / to request. */
export const FRAME_COUNT = USE_DUMMY_FRAMES ? DUMMY_FRAME_COUNT : REAL_FRAME_COUNT

/** Zero-padded frame filename, e.g. frame_0007.webp. */
export const framePath = (i: number): string =>
  `${FRAME_DIR}/frame_${String(i + 1).padStart(4, '0')}.webp`

/** Ordered, base-aware URLs for every frame in the sequence. */
export const frameUrls = (): string[] =>
  Array.from({ length: FRAME_COUNT }, (_, i) => asset(framePath(i)))

/* ---- Pinned-stage tuning (PRD §4: ~15–25px scroll / frame) ------------- *
 * heightVh drives total pin length. At 125 frames over ~275vh ≈ 22px/frame
 * on a 1080-tall viewport — inside the target band, so the scrub never steps.
 */
export const PIN_HEIGHT_VH = 300

/** Numeric scrub weight (never `true`) — heavy, eased glide. */
export const SCRUB_WEIGHT = 1.1

/**
 * Poster still for the Hero. In placeholder mode this is a dedicated
 * text-free frame (no baked-in HUD counter); once real frames land the
 * switch makes it the genuine opening frame.
 */
export const posterUrl = (): string =>
  asset(USE_DUMMY_FRAMES ? `${FRAME_DIR}/poster.webp` : framePath(0))
